### ISSUE TITLE
Documentation for validator

### ISSUE THREAD

**Issue by richard-drummond** [FHIR/latest-ig-publisher#1]
hi the documentation for using the fhir validator from the command line is great but non existent for using the validator classes programmatically.  Do you have some code that shows how to call the validator from java?  All my trials so far haven’t been a success.  The source code for the validator is not on git is it?

**Comment by grahamegrieve** [comment]
Source code is at https://github.com/hapifhir/org.hl7.fhir.core. See class org.hl7.fhir.r5.validation.ValidationEngine
